lint:
  files_exist:
    - lib/Utils.groovy
  files_unchanged:
    - .github/ISSUE_TEMPLATE/bug_report.yml
  schema_params: false
  template_strings: false
nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: Bailey PJ, Botvinnik O, Marques de Almeida F, Peltzer A, Sturm G
  description: Pipeline for processing 10x Genomics single cell rnaseq data
  force: false
  is_nfcore: true
  name: scrnaseq
  org: nf-core
  outdir: .
  version: 2.8.0dev
